apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    tier: flask-app
    app: shop
spec:
  selector:
    matchLabels:
      env: occ
  replicas: 1
  template:
    metadata:
      name: shop
      labels:
        env: occ
        app: shop
    spec:
      containers:
        - name: shop
          image: prabhu4029/assesment:v1
---
apiVersion: v1
kind: Service
metadata:
  name: shop
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8080
  selector:
    app: shop
    env: occ
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: occ-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /shop
          backend:
            serviceName: shop
            servicePort: 8080
        - path: /cart
          backend:
            serviceName: cart
            servicePort: 8080
        - path: /payment
          backend:
            serviceName: payment
            servicePort: 8080
        - path: /checkout
          backend:
            serviceName: checkout
            servicePort: 8080
